CREATE TABLE IF NOT EXISTS USER (
                      id BIGINT PRIMARY KEY AUTO_INCREMENT,
                      username VARCHAR(255) NOT NULL,
                      password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS ROLE (
                      id BIGINT PRIMARY KEY AUTO_INCREMENT,
                      name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS USERS_ROLES (
                             user_id BIGINT,
                             role_id BIGINT,
                             PRIMARY KEY (user_id, role_id),
                             FOREIGN KEY (user_id) REFERENCES USER(id),
                             FOREIGN KEY (role_id) REFERENCES ROLE(id)
);

INSERT INTO USER (PASSWORD, USERNAME)
SELECT '$2a$12$iPdRCGO4s7ZVaxgnFh1klOumqoQeHpAxdmrF077XjGC0MOFbhmrLm', 'user'
WHERE (SELECT COUNT(*) FROM USER) = 0;

INSERT INTO USER (PASSWORD, USERNAME)
SELECT '$2a$12$zoSsFHD4SCOM0A6HGdsLTOxKGAjTda9gWfTqTuVP2UmhWtoOVjTPO', 'admin'
WHERE (SELECT COUNT(*) FROM USER) = 1;

INSERT INTO ROLE (NAME)
SELECT 'ROLE_USER'
WHERE (SELECT COUNT(*) FROM ROLE) = 0;

INSERT INTO ROLE (NAME)
SELECT 'ROLE_ADMIN'
WHERE (SELECT COUNT(*) FROM ROLE) = 1;

INSERT INTO USERS_ROLES (USER_ID,ROLE_ID)
SELECT 1,1
WHERE (SELECT COUNT(*) FROM USERS_ROLES) = 0;

INSERT INTO USERS_ROLES (USER_ID,ROLE_ID)
SELECT 2,2
WHERE (SELECT COUNT(*) FROM USERS_ROLES) = 1;
-- INSERT INTO USER (PASSWORD,USERNAME)
-- VALUES('$2a$12$iPdRCGO4s7ZVaxgnFh1klOumqoQeHpAxdmrF077XjGC0MOFbhmrLm'
--       ,'user'),('$2a$12$zoSsFHD4SCOM0A6HGdsLTOxKGAjTda9gWfTqTuVP2UmhWtoOVjTPO'
--                ,'admin');

--
-- INSERT INTO ROLE (NAME)
-- VALUES ('ROLE_USER'),('ROLE_ADMIN');
-- INSERT INTO USERS_ROLES (USER_ID,ROLE_ID)
-- VALUES(1,1),(2,2);